export const CLICK_CREATE = 'CLICK_CREATE';
export const CLICK_TASK = 'CLICK_TASK';
export const CLICK_NEW_SIDEBAR = 'CLICK_NEW_SIDEBAR';
export const CLICK_DOING_SIDEBAR = 'CLICK_DOING_SIDEBAR';
export const CLICK_DONE_SIDEBAR = 'CLICK_DONE_SIDEBAR';
export const CLICK_ALLTASK_SIDEBAR = 'CLICK_ALLTASK_SIDEBAR';
export const SUBMIT_CREATE_TASK = 'SUBMIT_CREATE_TASK'
export const SUBMIT_EDIT_TASK = 'SUBMIT_EDIT';
export const RESET_FORM_EDIT = 'RESET_FORM_EDIT';
export const DELETE_FORM_EDIT = 'DELETE_FORM_EDIT';
export const SUBMIT_FORM_SEARCH = 'SUBMIT_FORM_SEARCH';
export const PUSH_DATA = 'PUSH_DATA'

